void challenge1();
void challenge2();
void challenge3();
void challenge4();
void challenge5();
void challenge6();
void challenge7();
void challenge8();
void challenge9();
void challenge10();
void challenge11();
void challenge12();
void (*challenges[12])() = {challenge1, challenge2, challenge3,challenge4,challenge5,challenge6,challenge7,challenge8,challenge9,challenge10,challenge11,challenge12};
